site_name: Nyrule Wiki

docs_dir: nyrule-wiki

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - content.tooltips

  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Ativar modo escuro
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Ativar modo claro

repo_url: https://github.com/NiiMiyo/obsidian-nyrule3/
edit_uri: blob/main/docs/

markdown_extensions:
  - markdown_captions
  - tables
  - abbr
  - md_in_html
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.mark

extra_css:
  - assets/css/text.css
  - assets/css/link.css
  - assets/css/table.css
  - assets/css/blockquote.css
  - assets/css/ul.css
  - assets/css/highlight.css
  - assets/css/columns.css
  - assets/css/figure.css
  - assets/css/headers.css

extra_javascript:
  - assets/js/add_classes.js

exclude_docs: |
  /.obsidian
  /.trash

plugins:
  - search

hooks:
  - mkdocs-hooks/make_index.py
  - mkdocs-hooks/add_title.py
  - mkdocs-hooks/obsidian_links.py
  - mkdocs-hooks/obsidian_comments.py
